### ISSUE TITLE
How to reproduce the EAE task result? 

### ISSUE THREAD

**Issue by cathyry** [osainz59/Ask2Transformers#16]
Excuse me,I want to reproduce the results in your team's paper: Textual Entailment for Event Argument Extraction: Zero and Few-Shot with Multi-Source Learning.However , readme.txt hadn't provide the full procedures to reproduce the Event Argument Extraction results.So I want to know how to reproduce  the result.

**Comment by osainz59** [comment]
Hi @cathyry ,
Thanks for reaching us, I will assume that you already have the [WikiEvents](https://github.com/raspberryice/gen-arg) and [ACE](https://catalog.ldc.upenn.edu/LDC2006T06) (preprocessed with the [OneIE](http://blender.cs.illinois.edu/software/oneie/) tool) datasets. 

If you just want to evaluate our pretrained models you can simply run the following command:
```bash
python -m a2t.evaluation --config resources/predefined_configs/ace.arguments.config.json
```
You can check the different configuration files on this directory: [resources/predefined_configs](https://github.com/osainz59/Ask2Transformers/tree/master/resources/predefined_configs)

We actually shared the models for zero-shot and full-train training settings, more information on the README file. In case you want to evaluate the few-shot checkpoints unfortunately you will have to train them by yourself, as they were too many for us to store them. If that is the case, you can train the models using the [run_glue.py](https://github.com/huggingface/transformers/blob/main/examples/pytorch/text-classification/run_glue.py) script from HuggingFace, the training splits are also shared on the [resources/](https://github.com/osainz59/Ask2Transformers/tree/master/resources/) directory.

In order to train your own models you will need to convert EAE examples to NLI format first, we had a [script](https://github.com/osainz59/Ask2Transformers/blob/master/scripts/wikievents2mnli.py) for that but is quite outdated since we performed a complete refactoring of the framework's code. The script will not work as it is but it should be straightforward to implement. 

The information about the hiperparameters can be found in the paper itself.

Let me know if there is something I can help you with,
Oscar

**Comment by JosephGatto** [comment]
Am I correct in assuming that, swapping out the pretrained models in this script for **ynie/roberta-large-snli_mnli_fever_anli_R1_R2_R3-nli** and **roberta-large-mnli** reproduce the results of Table 5? If so, is there expectation that the results can vary when compared to those reported in the paper?

**Comment by osainz59** [comment]
Yes, if you replace the `ynie/roberta-large-snli_mnli_fever_anli_R1_R2_R3-nli` with `roberta-large-mnli` you should obtain the results reported as NLI mnli only zero-shot.
